spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/oms
    username: tmckay
    password: tM031293

  jpa:
    hibernate:
      ddl-auto: none
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSZ
    mapper:
      DEFAULT_VIEW_INCLUSION: true

logging:
  level:
    root: INFO
    com.thetylermckay.backend: DEBUG
    
server:
  hosts:
    - http://localhost:3000
    - http://10.0.0.14:3000  resource_path: src/main/resources