jwt:
  accessTokenValidititySeconds: 14400 # 4 hours
  authorizedGrantTypes:
    - password
    - authorization_code
    - refresh_token
  clientId: thetylermckay-frontend
  clientSecret: secret
  refreshTokenValiditySeconds: 2592000 # 30 days
  signingKey: 123

logging:
  level:
    root: INFO
    com.thetylermckay.backend: DEBUG

server:
  hosts:
    - http://localhost:3000
    - http://10.0.0.14:3000  resource_path: src/main/resources
  
spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/oms
    username: tmckay
    password: tM031293

  jpa:
    hibernate:
      ddl-auto: none
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSZ
    mapper:
      DEFAULT_VIEW_INCLUSION: false