jwt:
  accessTokenValiditySeconds: 14400 # 4 hours
  authorized_grant_types:
    - password
    - authorization_code
    - refresh_token
  client_id: thetylermckay-frontend
  client_secret: secret
  refresh_token_validity_seconds: 2592000 # 30 days
  signing_key: 123

logging:
  level:
    root: INFO
    com.thetylermckay.backend: DEBUG

server:
  host: https://thetylermckay.com
  hosts:
    - http://thetylermckay.com
    - https://thetylermckay.com
  is_prod: true
  port: 443
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: tM031293
    key-store-type: pkcs12
    key-alias: tomcat
    key-password: tM031293
  resource_path: resources
  
spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/oms?serverTimezone=UTC
    username: hideand2
    password: tM031293!!!!
  mail:
    host: smtp.gmail.com
    port: 587
    username: tmckay1.jackson@gmail.com
    password: vlvxpwmegczscbku
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls:
            enable: true
  servlet:
    multipart:
      max-file-size: 10MB
      file-size-threshold: 5MB
      location: resources/tmp
      max-request-size: 5MB
      enabled: true

  jpa:
    hibernate:
      ddl-auto: none
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSZ
    mapper:
      DEFAULT_VIEW_INCLUSION: false